# service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
# deployement

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  # pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
